INSERT INTO resources (user_id, category_id, title, description, url, media_url, is_video, is_private)
VALUES
  (1, 1, '5 Front-end Development Skills to Land Your First Job', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.youtube.com/watch?v=-_X6PhkjpzU', 'https://www.youtube.com/watch?v=-_X6PhkjpzU', true, false),
  (1, 4, 'Prep to ace your interview', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.bloomtech.com/article/backend-developer-interview-questions', 'https://assets-global.website-files.com/615cc8f463d67d6b52e5bb6d/639995ad0771d2179ab919ff_A%20banner%20with%20a%20laptop%20and%20a%20coffee%20mug.webp', false, false),
  (1, 3, 'Full Stack Web Development for Beginners', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.youtube.com/watch?v=nu_pCVPKzTk', 'https://www.youtube.com/watch?v=nu_pCVPKzTk', true, false),
  (2, 4, 'Data Digest: AI, Governance, and Governments', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://tdwi.org/articles/2023/02/09/adv-all-ai-governance-0209.aspx', 'https://tdwi.org/articles/2023/02/09/-/media/TDWI/TDWI/BITW/AI11.jpg', false, false),
  (2, 5, 'Three Trends That Will Advance Citizen Analytics', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://tdwi.org/articles/2023/01/11/pm-all-three-trends-that-will-advance-citizen-analytics.aspx', 'https://tdwi.org/articles/2023/01/11/-/media/TDWI/TDWI/BITW/team.jpg', false, false),
  (3, 2, 'How to Become a Back-End Developer', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.youtube.com/watch?v=1gDdMv5FEuY', 'https://www.youtube.com/watch?v=1gDdMv5FEuY', true, false),
  (3, 2, 'What You Need to Know to be a Backend Developer', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.youtube.com/watch?v=0Kv_k4ypj6o', 'https://www.youtube.com/watch?v=0Kv_k4ypj6o', true, false),
  (3, 2, 'A Beginner Guide to Back-End Development', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.upwork.com/resources/beginners-guide-back-end-development', 'https://assets-global.website-files.com/5ec7dad2e6f6295a9e2a23dd/6220b28ac57f29ae453735b2_back-end-development-p-800.jpeg', false, false),
  (4, 3, 'Top skills a full stack developer should have', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.hackerearth.com/blog/developers/top-skills-a-full-stack-developer-should-have/', 'https://blog-c7ff.kxcdn.com/blog/wp-content/uploads/2015/11/blog_dev-01-1.jpg', false, true),
  (4, 5, 'Google Analytics Beginners Tutorial 2023', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'https://www.youtube.com/watch?v=njri8_gJTs0', 'https://www.youtube.com/watch?v=njri8_gJTs0', true, true)
;
